### ISSUE TITLE
How can include all depencies in the final index.js ?

### ISSUE THREAD

**Issue by Suniron** [egoist/tsup#619]
Hi,

I think that my question is about a basic usage but I can't find instruction in documentation or other issues and discussions..

So, I want to build a single **index.js** wich inclue all other typescript files (it's already good for that) and all depencies, on a typescript project.

Actually, if i do a `tsup src/index.ts` at root, a dist folder is built with the famous **index.js** inside.
But, this **index.js** work only in this **dist** folder (or at root of project). 

So, if I put this file on my production server (without any **package.json** or **node_modules** folder), and I do a `node index.js`, some error are printed to say that modules aren't found (**package.json** depencies).

Could you help me to find the correct arguments to include all depencies at build time 🙏.

Thanks by advance.

**Comment by OmgImAlexis** [comment]
Make sure you add the deps as development deps(`npm i -D package_name` and you should be good.

**Comment by tomglenn** [comment]
@OmgImAlexis This works but I'm not sure I understand why `tsup` works this way? Other bundlers (e.g. parcel, rollup etc) will bundle standard dependencies and not dev dependencies since they're typically reserved for packages that aren't needed to run the app in production like Jest or Babel.

Would you mind explaining the thought process behind this? For example, if I wanted to use the `uuid` package to generate random UUIDs in my app, it seems counter-intuitive to need to install that as a dev dependency.

I see there is a config flag to bypass this (e.g. `"noExternal": ["uuid"]`) but this quickly gets verbose if you're using a lot of third-party dependencies and cluttering the dev dependencies with deps that aren't dev tooling just seems wrong. Also perhaps it's just me but the name `noExternal` doesn't really seem to accurately describe what that config flag is used for. It would make more sense to be called `includeExternal`.

**Comment by OmgImAlexis** [comment]
So the difference is with tsup a dev dependency is seen as something needed during dev time. The reason it's not needed during production is because tsup is going to inline the code in the final bundle.

Think of this instead of shipping a lib, it's readme and all it's associated files you ship just the code you import as it's pulled into the bundle. If the dep you're pulling in is ESM even better as it should only pull in the exact functions, etc. you use and not the whole lib. This is a massive space saving and ensures you're only shipping the code you're actually using. This also reduces attack surfaces, etc.

>  but this quickly gets verbose if you're using a lot of third-party dependencies and cluttering the dev dependencies with deps that aren't dev tooling just seems wrong.

I think the issue is you're seeing "devDeps" as "devTools" when that's not the case. Dev deps are deps that needed during the dev process. Part of that process is the build process where dev tools and dev deps are used. In this case the dev deps are inlined so they're not needed once the build is done.

Sidenote: I'd use the built in https://nodejs.org/api/crypto.html#cryptorandomuuidoptions for UUID generation and not another lib.

**Comment by egoist** [comment]
think of it like this:

tsup bundles everything you imported by default, just like parcel or webpack, but "dependencies" and "peerDependencies" are externalized because they are available at runtime, since you usually use tsup to publish a library, whose  "dependencies" will be downloaded when user installs your library.

**Comment by tomglenn** [comment]
@OmgImAlexis @egoist Thank you both for taking the time to explain. While on the surface what you're saying makes logical sense (the packages do not need to be *imported* at runtime because they're already bundled in the final JS), it does not make semantic sense as per the NPM documentation (https://docs.npmjs.com/specifying-dependencies-and-devdependencies-in-a-package-json-file) whereby the description of `dependencies` is:

> Packages required by your application in production.

If I'm importing the `uuid` package into my application, semantically it is required by my application in production. Whether it's bundled into the final JS or not.

The definition for `devDependencies` is:

> Packages that are only needed for local development and testing.

I'm aware there are arguments for various approaches here (i.e. https://jsramblings.com/do-dependencies-devdependencies-matter-when-using-webpack/). But semantically, having all dependencies as devDependencies is confusing and not the JS standard way of developing. It also goes against the grain when it comes to the way other bundlers work, so it may just be worth making this a little clearer in the documentation and even explaining why `tsup` takes this approach.

Just as a side, I'm using this in a slightly different context to what I suspect most people are, in that I'm producing a JS bundle that is being used inside Goja (a Go implementation of ES5 - https://github.com/dop251/goja) so I don't have access to node modules at runtime. It also means I can't use Node built in features like `crypto`.

Apologies, I'm not trying to be argumentative for the sakes of it. But when swapping out `rollup` for `tsup` it had me confused for a good 30 minutes trying to understand why it wasn't bundling my external packages. So some clearer documentation here would be extremely helpful. It's briefly mentioned in your docs here https://tsup.egoist.sh/#excluding-packages but there is no mention of the `noExternal` flag anywhere on that page, for that you have to go to the API docs and even then the description for `noExternal` isn't immediately obvious what it does.

With all that said, I'm enjoying the speed of `tsup` very much so thank you for all your hard work.

**Comment by lvjiaxuan** [comment]
> Hi,
> 
> I think that my question is about a basic usage but I can't find instruction in documentation or other issues and discussions..
> 
> So, I want to build a single **index.js** wich inclue all other typescript files (it's already good for that) and all depencies, on a typescript project.
> 
> Actually, if i do a `tsup src/index.ts` at root, a dist folder is built with the famous **index.js** inside. But, this **index.js** work only in this **dist** folder (or at root of project).
> 
> So, if I put this file on my production server (without any **package.json** or **node_modules** folder), and I do a `node index.js`, some error are printed to say that modules aren't found (**package.json** depencies).
> 
> Could you help me to find the correct arguments to include all depencies at build time 🙏.
> 
> Thanks by advance.

Similar situation like mine.

I have tried to build a _Github Action_ bundle with tsup and [unbuild](https://github.com/unjs/unbuild), and then _Github Action_'s running result tells that the dependencies couldn't find.

At the first, I was wondering why tsup and unbuild are not bundling dependencies. After reading and googling, it occurred to me that these two bundle tool's building bundle is aiming at being installed to **another project** rather than doing `node index.js` directly.

Finally, I used esbuild for bundling all dependencies. 😂😂😂

**Comment by OmgImAlexis** [comment]
> Finally, I used esbuild for bundling all dependencies. 😂😂😂

Im really confused why you're not using tsup. It uses esbuild internally.

**Comment by danawoodman** [comment]
Would be super helpful to make a clear note of this in the readme. I had the same confusion as @tomglenn because of the same assumptions. A note to the effect of `put any dependencies you want to use in your package in devDependencies or else they won't be included in the output bundle` would be helpful :)

**Comment by mrksbnch** [comment]
I ran into the same issue when switching from `esbuild` to `tsup` (makes generating .d.ts files easier). One of the packages inside my monorepo (let's call it "Package A") uses a library from npm which is installed as a dependency. 

Another package ("Package B") is using "Package A" as a dependency but not the library from npm. When switching the build to use `tsup` instead of `esbuild`, I got an error saying that the "INSERT_LIBRARY_NAME_FROM_NPM could not be found". 

Installing the library from npm as a dependency for "Package B" or using the library from npm as a dev dependency inside "Package A" fixes this problem. However, as others have mentioned this seems counterintuitive, especially since bundling with `esbuild`—or any other bundler I'm aware of—works differently (it includes `dependencies` in the final bundle).

So, ideally this should at least be a setting in order to make `tsup` work similar to other bundlers.

**Comment by zfy0701** [comment]
default behavior of tsup make sense, but definitely nice to provider an option to bundle all dependencies.

e.g. we are building a lambda execution engine for people to upload bundle js file, in this case I don't want to use to upload both their package.json and bundle file, but only the js file

**Comment by rahul-sharma-uipath** [comment]
I ran into this same problem and was able to get around it by simply giving a wildcard as the regex for `noExternal` e.g. 
```
{
    target: 'node16',
    platform: 'node',
    noExternal: [ /(.*)/ ],
    ...rest of options
}
```

**Comment by He110te4m** [comment]
> > Finally, I used esbuild for bundling all dependencies. 😂😂😂
> 
> Im really confused why you're not using tsup. It uses esbuild internally.

In fact, I have the same problem and considering using `esbuild` instead of `tsup`.

The scenarios are:

I want to build a request library in monorepo to handle requests uniformly.
When used elsewhere, I don't need to worry about the runtime environment and the underlying implementation to use it.

Also, other projects that use this private package don't install specific request dependencies, such as `axios` and `node-fetch`, so I need to bundle all dependencies at build time.

The problem I have encountered is that with either `axios` or `node-fetch` configured as `noExternal`, the build product still contains other packages such as `url`, rather than building all the dependencies in `axios`.

**Comment by Akiyamka** [comment]
> So the difference is with tsup a dev dependency is seen as something needed during dev time. The reason it's not needed during production is because tsup is going to inline the code in the final bundle.

this is really weird! I thought it was a bug, but thanks to this track i found out it was meant to be.
esbuild is a good alternative except it can't generate d.ts files.

As an alternative, you could also consider https://github.com/developit/microbundle

**Comment by kettanaito** [comment]
The `noExternal` option is great but it doesn't affect the generated type definitions—those still import types from the package that no longer will be installed alongside the library (those imports will fail on the consumer's side). 

Is there any chance to make `noExternal` affect the `dts` option as well?

**Comment by rahul-sharma-uipath** [comment]
`dts` takes an option for `DtsConfig` which has an option for `resolve` - the `entry` option corresponds to the `entry` of the entire config, but then `resolve` takes a regex or string so you can bundle types you will need e.g
```
dts: {
    entry: 'src/index.ts',
    resolve: [ 'my-library' ],
} 
```

**Comment by kettanaito** [comment]
I definitely didn't know about that. Thank you, @rahul-sharma-uipath!

**Comment by lukechilds** [comment]
Just adding my 2c here, it would be great to have a simple flag to enable transpiling/bundling all of node_modules into the final bundle. Our usecase is packaging a Node.js project into a static binary with `pkg`. `pkg` fails to bundle third party esm dependencies so running all of node_modules through tsup allows our project to be run through `pkg` without issue.

Maybe our use case is not that common but it currently works with less config using `esbuild` directly that with `tsup`.

esbuild config:

```shell
esbuild source/cli.js --bundle --platform=node
```

tsup config:

```
tsup source/cli.js --target node18 --config tsup.config.ts
```

`tsup.config.ts`

```ts
export default {
  noExternal: [ /(.*)/ ],
}
```

It gets even messier if you want to exclude a single module from node_modules since `noExternal` appears to overwrite `external` so you need to exclude from both.

esbuild config:

```shell
esbuild source/cli.js --bundle --platform=node --external:module-to-ignore
```

tsup config:

```
tsup source/cli.js --target node18 --config tsup.config.ts
```

`tsup.config.ts`

```ts
export default {
	noExternal: [/^((?!(module-to-ignore)).)*$/],
	external: [ 'module-to-ignore' ],
}
```

It would be really great if we didn't have to create a config file and could just pass a simple flag like:

```
tsup source/cli.js --target node18 --include-node-modules
```

**Comment by nicoduesing** [comment]
The trick with ` noExternal: [ /(.*)/ ],` sadly only works with tsup `6.2.1` or smaller. With `6.2.2`, something was changed, so now an error is thrown: 
```
✘ [ERROR] Could not resolve "my-dependency"

    src/index.ts:6:57:
      6 │ import * from "my-dependency";
        ╵               ~~~~~~~~~~~~~~~

  You can mark the path my-dependency" as external to exclude it from the bundle, which will
  remove this error.
```
It suggests to mark it as external, which is not, what I want. I want it to be bundled into the `dist/index.js` file.
Also a bit strange that a patch version includes such a radical change.

**Comment by 0xmaayan** [comment]
I followed this thread and there are some great comments here! tho I couldn't find a solution to my use case (which I think  is pretty common).

My package has a `peerDependency` listed in its `package.json`. I use this peerDependency package in my code with the `import` statement

```
import {Module} from "peer-dependency"
import type {Type} from "peer-dependency/types"
```

When trying to build my package, I am getting a `dts` error (esm and cjs built successfully) 
```
error TS2307: Cannot find module 'peer-dependency' or its corresponding type declarations.
error TS2307: Cannot find module 'peer-dependency/types' or its corresponding type declarations.
```

I tried @rahul-sharma-uipath suggestion and added it to the `dts` config on my `tsup` file
```
dts: { resolve: ["peer-dependency","peer-dependency/types"] }
```
also tried to mark it as `external`.

The only solution I found is to add the `peer-dependency` as a `devDependency` which feels a bit redundant as if I have a peerDependency we could safely assume that I use it for dev. Also, when trying to test my package with another local package (using link), since the dependency is under `devDependency` the local package that tests my package adds it to its dependency tree and I cant test some of the package logic (like make sure the dependency is installed in the local package before using the package peer-dependency module).

**Comment by fabiopolimeni** [comment]
Definitely unexpected bizarre behaviour, which fixed the same issue I had

**Comment by iursevla** [comment]
I ended up using  `noExternal` + `splitting:false` for my use case

```ts
import { defineConfig } from 'tsup';

export default defineConfig({
  format: ['esm'],
  entry: ['./src/index.ts'],
  dts: false,
  shims: true,
  skipNodeModulesBundle: true,
  clean: true,
  target: 'node20',
  platform: 'node',
  minify: true,
  bundle: true,
  // https://github.com/egoist/tsup/issues/619
  noExternal: [ /(.*)/ ],
  splitting: false,
});
``

**Comment by zhuoqun-chen** [comment]
> I ended up using `noExternal` + `splitting:false` for my use case
> 
> import { defineConfig } from 'tsup';
> 
> export default defineConfig({
>   format: ['esm'],
>   entry: ['./src/index.ts'],
>   dts: false,
>   shims: true,
>   skipNodeModulesBundle: true,
>   clean: true,
>   target: 'node20',
>   platform: 'node',
>   minify: true,
>   bundle: true,
>   // https://github.com/egoist/tsup/issues/619
>   noExternal: [ /(.*)/ ],
>   splitting: false,
> });
> ``

Thank you, this solution saved my day! I need to bundle all deps into my `main.js` to run in vscode webview extension
