### ISSUE TITLE
Build error `error: Expected ":" but found "file"` when I upgrade tsup from 5.9.0 to 5.9.1

### ISSUE THREAD

**Issue by laozhu** [egoist/tsup#471]
# My environment

- macOS
- node: v17.0.1
- yarn v1.22.17
- tsup v5.9.1

# My `tsup.config.ts`

```ts
import path from 'path';
import { defineConfig } from 'tsup';

import packageJson from './package.json';

export default defineConfig(({ outDir, platform, target, watch }) => {
  const isProd = !watch;

  return {
    entryPoints: ['src/*.ts', '!src/*.d.ts', '!src/*.test.ts'],
    outDir: outDir ?? path.join(__dirname, 'dist'),

    babel: false,
    clean: isProd,
    dts: true,
    external: ['react', 'react-dom', 'react-router-dom'],
    format: isProd ? ['cjs', 'esm'] : ['esm'],
    minify: isProd,
    platform: platform ?? 'browser',
    replaceNodeEnv: isProd,
    skipNodeModulesBundle: true,
    splitting: false,
    sourcemap: isProd ? 'external' : 'inline',
    target: target ?? 'es2018',
    watch: isProd ? false : 'src',

    define: {
      __BUILD_TIME__: Date.now().toString(),
      __DEV__: JSON.stringify(!isProd),
      __VERSION__: JSON.stringify(packageJson.version),
    },

    esbuildPlugins: [],
  };
});
```

# Build result with tsup v5.9.1

```bash
$ tsup
 > ../../node_modules/tsup/dist/index.js:13735:10: error: Expected ":" but found "file"
    13735 │         ""file:///Users/Ritchie/Developer/@fastcms/fastcms/node_modules/tsup/dist/index.js"": "importMetaUrlShim"
          ╵           ~~~~

Error: Build failed with 1 error:
../../node_modules/tsup/dist/index.js:13735:10: error: Expected ":" but found "file"
    at failureErrorWithLog (/Users/Ritchie/Developer/@fastcms/fastcms/node_modules/esbuild/lib/main.js:1493:15)
    at /Users/Ritchie/Developer/@fastcms/fastcms/node_modules/esbuild/lib/main.js:1151:28
    at runOnEndCallbacks (/Users/Ritchie/Developer/@fastcms/fastcms/node_modules/esbuild/lib/main.js:941:63)
    at buildResponseToResult (/Users/Ritchie/Developer/@fastcms/fastcms/node_modules/esbuild/lib/main.js:1149:7)
    at /Users/Ritchie/Developer/@fastcms/fastcms/node_modules/esbuild/lib/main.js:1258:14
    at /Users/Ritchie/Developer/@fastcms/fastcms/node_modules/esbuild/lib/main.js:629:9
    at handleIncomingPacket (/Users/Ritchie/Developer/@fastcms/fastcms/node_modules/esbuild/lib/main.js:726:9)
    at Socket.readFromStdout (/Users/Ritchie/Developer/@fastcms/fastcms/node_modules/esbuild/lib/main.js:596:7)
    at Socket.emit (node:events:390:28)
    at addChunk (node:internal/streams/readable:324:12)
error Command failed with exit code 1.
```

# Build result with tsup v5.9.0

```bash
$ tsup
CLI Building entry: src/debug.ts, src/index.ts, src/probe.ts
CLI Using tsconfig: tsconfig.json
CLI tsup v5.9.0
CLI Using tsup config: /Users/Ritchie/Developer/@fastcms/fastcms/libs/utilities/tsup.config.ts
CLI Target: es2018
CLI Cleaning output folder
CJS Build start
ESM Build start
ESM Build success in 9ms
CJS Build success in 12ms
DTS Build start
DTS Build success in 1468ms
✨  Done in 2.70s.
```

# Expected result with tsup v5.9.1

No error, the same with tsup v5.9.0.

**Comment by zhmushan** [comment]
Can't reproduce, can you give me a repo link to help locate the problem.

**Comment by egoist** [comment]
I'm working on a fix in `bundle-require`, it's likely `tsup` is installed a parent directory but `bundle-require` will only exclude packages in `$cwd/node_modules`

**Comment by egoist** [comment]
I'm working on a fix in `bundle-require`, it's likely `tsup` is installed a parent directory but `bundle-require` will only exclude packages in `$cwd/node_modules`

**Comment by egoist** [comment]
should be fixed now, reinstall tsup to update its dependencies

**Comment by laozhu** [comment]
@egoist thank you for quick reply, the above error has gone, but I have another error message now.

```bash
~/D/@/fastcms ❯❯❯ yarn add tsup --dev -W
yarn add v1.22.17
[1/5] 🔍  Validating package.json...
[2/5] 🔍  Resolving packages...
[3/5] 🚚  Fetching packages...
[4/5] 🔗  Linking dependencies...
[5/5] 🔨  Building fresh packages...
success Saved lockfile.
success Saved 14 new dependencies.
info Direct dependencies
└─ tsup@5.9.1
info All dependencies
├─ bundle-require@2.1.6
├─ cac@6.7.12
├─ import-cwd@3.0.0
├─ import-from@3.0.0
├─ joycon@3.0.1
├─ mz@2.7.0
├─ postcss-load-config@3.1.0
├─ rollup@2.60.1
├─ sucrase@3.20.3
├─ thenify-all@1.6.0
├─ thenify@3.3.1
├─ tree-kill@1.2.2
├─ ts-interface-checker@0.1.13
└─ tsup@5.9.1
$ patch-package
patch-package 6.4.7
Applying patches...
No patch files found
$ husky install
husky - Git hooks installed
✨  Done in 7.35s.
~/D/@/fastcms ❯❯❯ cd libs/utilities/
~/D/@/f/l/utilities ❯❯❯ yarn build
yarn run v1.22.17
$ tsup
Error: Cannot find module './impl/format'
Require stack:
- /Users/Ritchie/Developer/@fastcms/fastcms/node_modules/bundle-require/dist/index.js
- /Users/Ritchie/Developer/@fastcms/fastcms/node_modules/tsup/dist/chunk-NDMVZGWU.js
- /Users/Ritchie/Developer/@fastcms/fastcms/node_modules/tsup/dist/index.js
- /Users/Ritchie/Developer/@fastcms/fastcms/node_modules/tsup/dist/chunk-GGMAIU5L.js
- /Users/Ritchie/Developer/@fastcms/fastcms/node_modules/tsup/dist/chunk-EPL3FZVH.js
- /Users/Ritchie/Developer/@fastcms/fastcms/node_modules/tsup/dist/cli-default.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at /Users/Ritchie/Developer/@fastcms/fastcms/node_modules/bundle-require/dist/index.js:72:23
    at /Users/Ritchie/Developer/@fastcms/fastcms/node_modules/bundle-require/dist/index.js:62:17
    at node_modules/.pnpm/jsonc-parser@3.0.0/node_modules/jsonc-parser/lib/umd/main.js (/Users/Ritchie/Developer/@fastcms/fastcms/node_modules/bundle-require/dist/index.js:68:7)
    at __require (/Users/Ritchie/Developer/@fastcms/fastcms/node_modules/bundle-require/dist/index.js:29:44)
    at Object.<anonymous> (/Users/Ritchie/Developer/@fastcms/fastcms/node_modules/bundle-require/dist/index.js:194:38)
    at Module._compile (node:internal/modules/cjs/loader:1095:14)
error Command failed with exit code 1.
```

**Comment by egoist** [comment]
@laozhu please try again

**Comment by laozhu** [comment]
@egoist fixed with v5.9.2, thank you for your great work 👍
