### ISSUE TITLE
[8.5.1] Cannot find module './types.cts'

### ISSUE THREAD

**Issue by jlowcs** [egoist/tsup#1375]
I'm getting a typescript error when updating from 8.5.0 to 8.5.1:

```
node_modules/tsup/dist/index.d.ts:3:41 - error TS2307: Cannot find module './types.cts' or its corresponding type declarations.

3 import { SectionedSourceMapInput } from './types.cts';
```

**Comment by moltar** [comment]
Same here. I'm importing `tsup` types for some other build tool wrapper:

```
RollupError: Could not resolve "./types.cts" from "node_modules/tsup/dist/index.d.ts"
    at getRollupError (.../node_modules/.pnpm/rollup@4.34.9/node_modules/rollup/dist/shared/parseAst.js:285:41)
    at Object.error (.../node_modules/.pnpm/rollup@4.34.9/node_modules/rollup/dist/shared/parseAst.js:281:42)
    at ModuleLoader.handleInvalidResolvedId (.../node_modules/.pnpm/rollup@4.34.9/node_modules/rollup/dist/shared/rollup.js:22198:36)
    at .../node_modules/.pnpm/rollup@4.34.9/node_modules/rollup/dist/shared/rollup.js:22158:26
Error: error occurred in dts build
    at Worker.<anonymous> (.../node_modules/.pnpm/tsup@8.5.1_@swc+core@1.6.6_postcss@8.5.6_tsx@4.20.6_typescript@5.9.3_yaml@2.8.1/node_modules/tsup/dist/index.js:1545:26)
    at Worker.emit (node:events:518:28)
    at MessagePort.<anonymous> (node:internal/worker:268:53)
    at [nodejs.internal.kHybridDispatch] (node:internal/event_target:827:20)
    at MessagePort.<anonymous> (node:internal/per_context/messageport:23:28)
DTS Build error
```

**Comment by louiszn** [comment]
Any updates? Updating to 8.5.1 also broke `tsc --noEmit` for me

**Comment by ognis1205** [comment]
Same here.
